// net_sanitize.h -- M8 privacy sanitizer for network captures (Wiimmfi
// meta epic, capture/replay at the Ethernet backend boundary). See
// net_capture.h for the file format this operates on, and
// docs/m8-capture-replay-design.md for the overall M8 design.
//
// This module is pure, dependency-free byte manipulation -- no melonDS,
// emulator, or net_ring dependency -- on purpose: it is directly ported to
// tools/net_capture_tool.py's independent Python re-implementation (so a
// capture can be sanitized without building/running the emulator at all),
// and is independently unit-testable (runner/tests/net_capture_test.cpp).
//
// ---- Design: rewrite ONE learned identity, never "every MAC-shaped
// field" -----------------------------------------------------------------
// An earlier version of this sanitizer rewrote WHATEVER 6-byte value it
// found at a recognized MAC-shaped field position (Ethernet src/dst, ARP
// hardware addresses, BOOTP chaddr, DHCP option 61). That is wrong: a
// captured session also contains MACs that are NOT the console's
// identity and must NEVER be touched --
//   - the Ethernet broadcast address (FF:FF:FF:FF:FF:FF) and multicast
//     addresses (IEEE 802 I/G bit set) -- protocol constants, not
//     identifying, and
//   - this project's OWN host-side virtual infrastructure: the virtual
//     AP's BSSID (patches/0001-wifi-ap-identity.patch) and libslirp's
//     synthesized virtual-gateway/DHCP-server MAC -- also not
//     identifying (they're generated by this project's own code, not the
//     owner's hardware).
// Rewriting either category is not just an unnecessary privacy overreach,
// it is a CORRECTNESS BUG: confirmed empirically (beads Wiimmfi M8) that
// sanitizing a DHCP OFFER's broadcast Ethernet destination made melonDS's
// own WifiAP::RecvPacket destination-address filter silently drop the
// frame before the guest's DHCP client ever saw it, and sanitizing the
// virtual DHCP server's own synthesized MAC broke a later exchange the
// same way.
//
// The fix: this sanitizer rewrites EXACTLY ONE MAC per capture session --
// the console's own real identity -- and leaves every other MAC-shaped
// value completely untouched, everywhere. That one MAC is LEARNED, not
// configured: the Ethernet SOURCE address of the first TX-direction
// (guest -> host) frame is, by construction, always the console's own
// real hardware address (nothing else could legitimately appear there).
// Once learned, every occurrence of that exact 6-byte value anywhere in
// any frame (Ethernet header, ARP payload, BOOTP chaddr, DHCP option 61)
// -- in EITHER direction -- is rewritten to the same stable synthetic
// substitute; nothing else is ever touched. This is simultaneously more
// privacy-correct (only the genuinely identifying value is touched) and
// protocol-safe (every other address a real DHCP/ARP exchange legitimately
// uses -- broadcast, multicast, the AP, the virtual DHCP server -- passes
// through byte-for-byte).
//
// "Stable" mapping: the SAME learned identity always maps to the SAME
// synthetic replacement for the lifetime of one NdsNetSanitizeState (one
// capture file), so a sanitized capture stays internally consistent and
// still replays correctly. The mapping is further made STATELESS/
// deterministic (derived by hashing the identity's bytes, not by
// insertion order), so the same real MAC always sanitizes to the same
// synthetic value even across separate capture files, or between this
// C++ implementation and the Python port (tools/net_capture_tool.py) --
// a bonus beyond what the task strictly requires, and also exactly what
// lets net_replay.cpp's comparison re-derive the same mapping from a
// fresh state (see that file's own doc comment).
//
// Concretely, once the identity MAC is known, this rewrites every
// occurrence of it at:
//   - Ethernet header source/destination (offsets 0/6).
//   - ARP (EtherType 0x0806) sender/target hardware address fields.
//   - DHCP/BOOTP (UDP 67/68) `chaddr` (client hardware address), when
//     htype=1/hlen=6 (Ethernet) and it equals the identity MAC.
//   - DHCP option 61 (Client Identifier), when it has the standard
//     htype=1 + 6-byte-MAC shape and the MAC equals the identity MAC.
// DHCP option 12 (Host Name) is separately replaced with a stable
// synthetic ASCII string of the SAME byte length (so no other offset in
// the frame shifts), keyed by the original string -- a hostname has no
// "is this the console's identity" ambiguity the way a MAC field does
// (this project's own capture only ever carries one hostname source, the
// console's own), so it does not need the identity-learning treatment.
//
// IPv4 addresses, ports, timestamps, and checksums (other than the UDP
// checksum recompute this same function performs when it changes payload
// bytes) are intentionally left untouched: they are assigned by this
// project's OWN virtual AP/DHCP server, not the owner's real-world
// identity, and rewriting them would break the very "same lease" A/B this
// milestone's replay proof exists to make (see the task's acceptance bar
// -- the recorded lease address must still read back identically).
//
// Deliberately OUT OF SCOPE: TLS-layer identifiers (e.g. any console ID
// exchanged during real NAS auth) cannot be rewritten here -- by the time
// such a value would appear on the wire it is inside an encrypted TLS
// record, so byte-level rewriting is not possible without breaking the
// handshake. Avoiding capture of that material requires not capturing/
// committing that exchange at all (this project's existing session-
// random / never-record policy, docs/networking-observability-plan.md
// section (g)) rather than sanitizing it after the fact. This module does
// not claim to solve that; see the M8 report's "unresolved" list.

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

// direction convention matches NdsNetTraceEntry::direction /
// NdsNetCaptureRecord::direction exactly: 0 = guest->host (TX/egress),
// 1 = host->guest (RX/ingress).
constexpr uint8_t kNdsNetSanitizeDirTx = 0;
constexpr uint8_t kNdsNetSanitizeDirRx = 1;

// Per-capture sanitizer state. One instance's lifetime should span exactly
// one capture file (construct fresh per NdsNetCaptureWriter / per
// standalone sanitize pass).
class NdsNetSanitizeState {
public:
    // Learns the console's own identity MAC from a TX-direction frame's
    // Ethernet source address, if not already learned. A no-op once an
    // identity is already known (a session has exactly one console
    // identity; a later call is never expected to disagree, but if it
    // ever did, the FIRST-learned identity wins rather than silently
    // re-deriving a second mapping mid-session).
    void LearnIdentityFromTxSource(const uint8_t eth_src[6]);
    bool HasIdentity() const { return has_identity_; }
    const std::array<uint8_t, 6>& IdentityMac() const { return identity_mac_; }

    // Stable synthetic MAC for `mac` (6 bytes) -- locally-administered
    // (bit 1 of the first octet set) and unicast (bit 0 clear), so it can
    // never collide with a real vendor-assigned address, matching this
    // project's existing convention for synthetic MACs (see
    // runner/vendor/melonds/patches/0001-wifi-ap-identity.patch's BSSID).
    // Exposed as a general primitive (net_replay.cpp calls it directly to
    // independently re-derive the synthetic value for the identity MAC it
    // learns on the replay side) but net_sanitize_ethernet_frame below
    // only ever calls it with the ONE learned identity MAC, never with an
    // arbitrary MAC-shaped field's contents.
    std::array<uint8_t, 6> MapMac(const uint8_t mac[6]);

    // Stable, length-preserving replacement hostname bytes (DHCP option
    // 12), keyed by the original bytes.
    std::vector<uint8_t> MapHostname(const uint8_t* data, size_t len);

private:
    static uint64_t PackMac(const uint8_t mac[6]);

    bool has_identity_ = false;
    std::array<uint8_t, 6> identity_mac_{};
    std::unordered_map<uint64_t, std::array<uint8_t, 6>> mac_cache_;
    std::unordered_map<std::string, std::vector<uint8_t>> hostname_cache_;
};

// Sanitizes one Ethernet frame IN PLACE (Ethernet header + ARP + DHCP, per
// the design note above). `frame`/`len` follow the same "complete on-the-
// wire Ethernet II frame, no FCS" convention as net_classify_ethernet_
// frame (runner/src/net/net_classify.h). `direction` is
// kNdsNetSanitizeDirTx/Rx -- used ONLY to learn the identity MAC from a
// TX frame's source address the first time one is seen; rewriting itself
// applies identically regardless of direction once the identity is known.
// Returns true if any byte was modified. Never reads or writes past
// `len`; a malformed/truncated header for a given protocol layer simply
// skips that layer's rewriting -- same "best-effort, never guess past the
// bytes actually present" convention as net_classify.cpp. If no identity
// has been learned yet (i.e. an RX frame arrives before any TX frame ever
// has -- not expected for this project's own DHCP-first flows, but
// possible in principle), no MAC-shaped field is rewritten at all (there
// is nothing yet known to be sensitive); the hostname option is still
// rewritten regardless, since it needs no identity to be meaningful.
bool net_sanitize_ethernet_frame(uint8_t* frame, size_t len, uint8_t direction,
                                  NdsNetSanitizeState& state);

// Wiimmfi M8 replay support ONLY -- never used for anything that gets
// stored/committed. The mirror operation of net_sanitize_ethernet_frame,
// for the REPLAY DELIVERY path (see net_replay.cpp): a sanitized
// capture's stored frames have the console's real MAC rewritten to a
// stable synthetic value wherever it appears -- but the LIVE guest
// receiving a replayed RX frame validates address-identifying fields
// against its OWN real identity (concretely: a DHCP client checking that
// a DHCPOFFER/ACK's `chaddr` echoes its own hardware address before
// accepting the lease -- confirmed empirically: delivering the sanitized
// bytes as-is made the guest reject the OFFER and retry DISCOVER
// indefinitely instead of completing the handshake). This function walks
// the SAME field positions net_sanitize_ethernet_frame rewrites and
// substitutes any occurrence of `synthetic_mac` back to `real_mac`
// wherever it appears as a whole 6-byte MAC-shaped value. This works
// despite the forward mapping being a one-way hash (not invertible in
// general) because there is only ONE real identity being replayed per
// session, learned directly from the live guest's own outgoing frames
// (see net_replay.cpp) -- so no inversion of the hash is actually needed,
// only substitution of one already-known 6-byte value for another.
void net_desanitize_ethernet_frame_for_replay(uint8_t* frame, size_t len,
                                                const uint8_t synthetic_mac[6],
                                                const uint8_t real_mac[6]);
