#!/usr/bin/env python3
"""Accumulate observed Tier-3 entries into content-validated bank configs.

Run this after an LLE traversal on a native server started with
--discover-static-misses. Existing entries are merged, so successive menu
scenarios monotonically grow the static corpus. The binary images themselves
remain ignored under generated/firmware_capture; only addresses/modes and
their image identities are written to the checked-in configs.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "oracle"))

from _client import DebugClient  # noqa: E402


ENTRY_RE = re.compile(
    r"\[\[entry_point\]\]\s*\n"
    r"addr\s*=\s*(0x[0-9A-Fa-f]+|\d+)\s*\n"
    r"mode\s*=\s*\"(arm|thumb)\"",
    re.MULTILINE,
)


def existing_entries(path: Path) -> set[tuple[int, str]]:
    if not path.exists():
        return set()
    return {(int(addr, 0), mode) for addr, mode in ENTRY_RE.findall(path.read_text())}


def render_config(spec: dict, entries: set[tuple[int, str]]) -> str:
    lines = [
        "# AUTO-GENERATED by tools/export_firmware_bank_configs.py.",
        "# Inputs are guest-produced LLE captures; runtime dispatch validates",
        "# every generated function against the current live guest bytes.",
        "",
        "[program]",
        f'name         = "{spec["name"]}"',
        f'id           = "{spec["id"]}"',
        f'cpu          = "{spec["cpu"]}"',
        f'isa          = "{spec["isa"]}"',
        f'load_address = 0x{spec["load"]:08X}',
        f'size         = 0x{spec["size"]:08X}',
        f'entry_pc     = 0x{spec["entry"]:08X}',
        "",
        "[identity]",
        f'sha1 = "{spec["sha1"]}"',
        "",
    ]
    for copy in spec.get("copies", []):
        lines += [
            "[[code_copy]]",
            f'runtime_start = 0x{copy[0]:08X}',
            f'source_start  = 0x{copy[1]:08X}',
            f'size          = 0x{copy[2]:08X}',
            f'name          = "{copy[3]}"',
            "",
        ]
    for addr, mode in sorted(entries):
        lines += [
            "[[entry_point]]",
            f"addr = 0x{addr:08X}",
            f'mode = "{mode}"',
            'kind = "runtime_observed"',
            "",
        ]
    return "\n".join(lines)


def export_scenario_variant(capture_path: Path, out_dir: Path) -> int:
    """Create one content-validated bank per CPU from a traversal capture."""
    capture = json.loads(capture_path.read_text(encoding="utf-8"))
    if capture.get("format") != 1 or not capture.get("safe_name"):
        raise SystemExit(f"unsupported scenario capture: {capture_path}")
    banks = {int(item["cpu"]): item for item in capture["banks"]}
    coverage = capture["coverage"]
    roots = capture["roots"]
    safe_name = capture["safe_name"]
    specs = []
    if roots.get("9") is not None:
        specs.append({
            "file": f"fw_arm9_{safe_name}.toml",
            "name": f"NDS ARM9 firmware ({capture['scenario']} generation)",
            "id": f"fw_arm9_{safe_name}",
            "cpu": "arm9", "isa": "armv5te",
            "load": 0x01FF8000, "size": 0x00408000,
            "entry": int(roots["9"]["pc"]),
            "entry_mode": "thumb" if roots["9"]["thumb"] else "arm",
            "sha1": banks[9]["sha1"],
            "ranges": [(0x01FF8000, 0x02400000)],
        })
    if roots.get("7") is not None:
        specs.append({
            "file": f"fw_arm7_{safe_name}.toml",
            "name": f"NDS ARM7 firmware ({capture['scenario']} generation)",
            "id": f"fw_arm7_{safe_name}",
            "cpu": "arm7", "isa": "armv4t",
            "load": 0x02000000, "size": 0x00418000,
            "entry": int(roots["7"]["pc"]),
            "entry_mode": "thumb" if roots["7"]["thumb"] else "arm",
            "sha1": banks[7]["sha1"],
            "ranges": [
                (0x02000000, 0x02400000),
                (0x037F8000, 0x03810000),
            ],
            "copies": [
                (0x037F8000, 0x02400000, 0x00018000,
                 "scenario ARM7 WRAM source copy"),
            ],
        })

    out_dir.mkdir(parents=True, exist_ok=True)
    counts: dict[str, int] = {}
    for spec in specs:
        wanted_cpu = 9 if spec["cpu"] == "arm9" else 7
        path = out_dir / spec["file"]
        entries = existing_entries(path)
        entries.update(
            (int(item["pc"]), "thumb" if item["thumb"] else "arm")
            for item in coverage
            if int(item["cpu"]) == wanted_cpu and any(
                start <= int(item["pc"]) < end
                for start, end in spec["ranges"]
            )
        )
        entries.add((spec["entry"], spec["entry_mode"]))
        path.write_text(render_config(spec, entries), encoding="utf-8", newline="\n")
        counts[spec["id"]] = len(entries)

    print(json.dumps({
        "capture": str(capture_path),
        "observed": len(coverage),
        "configs": counts,
    }, indent=2))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--port", type=int, default=19852)
    parser.add_argument("--out", type=Path, default=ROOT / "bios" / "firmware_banks")
    parser.add_argument(
        "--capture-dir", type=Path,
        default=ROOT / "generated" / "firmware_capture",
    )
    parser.add_argument(
        "--capture-manifest", type=Path,
        help="export only the variants described by a scenario capture JSON",
    )
    args = parser.parse_args()

    if args.capture_manifest is not None:
        return export_scenario_variant(args.capture_manifest, args.out)

    manifest = json.loads((args.capture_dir / "manifest.json").read_text())
    captures = {item["name"]: item for item in manifest["captures"]}
    specs = [
        {
            "file": "fw_arm9_early.toml", "capture": "fw_arm9_early",
            "name": "NDS ARM9 firmware (early generation)",
            "id": "fw_arm9_early", "cpu": "arm9", "isa": "armv5te",
            "load": 0x01FF8000, "size": 0x00408000, "entry": 0x021F0000,
            "accept": lambda pc: 0x02000000 <= pc < 0x02400000
                                 or 0x01FF8000 <= pc < 0x02000000,
        },
        {
            "file": "fw_arm9_menu.toml", "capture": "fw_arm9_menu",
            "name": "NDS ARM9 firmware (menu generation)",
            "id": "fw_arm9_menu", "cpu": "arm9", "isa": "armv5te",
            "load": 0x01FF8000, "size": 0x00408000, "entry": 0x021F0000,
            "accept": lambda pc: 0x02000000 <= pc < 0x02400000
                                 or 0x01FF8000 <= pc < 0x02000000,
        },
        {
            "file": "fw_arm7_early.toml", "capture": "fw_arm7_early",
            "name": "NDS ARM7 firmware (early generation)",
            "id": "fw_arm7_early", "cpu": "arm7", "isa": "armv4t",
            "load": 0x03800000, "size": 0x00010000, "entry": 0x0380F800,
            "accept": lambda pc: 0x03800000 <= pc < 0x03810000,
        },
        {
            "file": "fw_arm7_intermediate.toml",
            "capture": "fw_arm7_intermediate",
            "name": "NDS ARM7 firmware (intermediate generation)",
            "id": "fw_arm7_intermediate", "cpu": "arm7", "isa": "armv4t",
            "load": 0x037F8000, "size": 0x00018000, "entry": 0x0380F8D0,
            "entry_mode": "thumb",
            "accept": lambda pc: 0x03800000 <= pc < 0x03810000
                                 or 0x037F8000 <= pc < 0x03800000,
        },
        {
            "file": "fw_arm7_shared_ready.toml",
            "capture": "fw_arm7_shared_ready",
            "name": "NDS ARM7 firmware (shared-code generation)",
            "id": "fw_arm7_shared_ready", "cpu": "arm7", "isa": "armv4t",
            "load": 0x037F8000, "size": 0x00018000, "entry": 0x037FA600,
            "accept": lambda pc: 0x03800000 <= pc < 0x03810000
                                 or 0x037F8000 <= pc < 0x03800000,
        },
        {
            "file": "fw_arm7_irq_ready.toml",
            "capture": "fw_arm7_irq_ready",
            "name": "NDS ARM7 firmware (runtime IRQ generation)",
            "id": "fw_arm7_irq_ready", "cpu": "arm7", "isa": "armv4t",
            "load": 0x037F8000, "size": 0x00018000, "entry": 0x037FD798,
            "accept": lambda pc: 0x03800000 <= pc < 0x03810000
                                 or 0x037F8000 <= pc < 0x03800000,
        },
        {
            "file": "fw_arm7_menu.toml", "capture": "fw_arm7_menu",
            "name": "NDS ARM7 firmware (menu generation)",
            "id": "fw_arm7_menu", "cpu": "arm7", "isa": "armv4t",
            "load": 0x037F8000, "size": 0x00018000, "entry": 0x0380F800,
            "accept": lambda pc: 0x03800000 <= pc < 0x03810000
                                 or 0x037F8000 <= pc < 0x03800000,
        },
    ]
    for spec in specs:
        spec["sha1"] = captures[spec["capture"]]["sha1"]

    client = DebugClient(port=args.port, timeout=60.0)
    try:
        observed = client.cmd("tier3_coverage", max=262144)["entries"]
    finally:
        client.close()

    args.out.mkdir(parents=True, exist_ok=True)
    counts = {}
    for spec in specs:
        path = args.out / spec["file"]
        entries = existing_entries(path)
        wanted_cpu = 9 if spec["cpu"] == "arm9" else 7
        entries.update(
            (item["pc"], "thumb" if item["thumb"] else "arm")
            for item in observed
            if item["cpu"] == wanted_cpu and spec["accept"](item["pc"])
        )
        entries.add((spec["entry"], spec.get("entry_mode", "arm")))
        path.write_text(render_config(spec, entries), newline="\n")
        counts[spec["id"]] = len(entries)

    print(json.dumps({"observed": len(observed), "configs": counts}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
