"""Regenerate vendor/freebios/freebios_images.{cpp,h} — the FreeBIOS images
the runner embeds for --freebios — from the third_party/freebios submodule
(github.com/mstan/freebios, an unmodified mirror of melonDS's freebios/,
BSD-2-Clause)."""

import hashlib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SUB = REPO / "third_party" / "freebios"
OUT = REPO / "vendor" / "freebios"

IMAGES = [
    ("drastic_bios_arm9.bin", "nds_freebios9",
     "b85d6afdbf65d87c9ab11d4e7fb5ecfd6192ccf8"),
    ("drastic_bios_arm7.bin", "nds_freebios7",
     "eaab9b21610978f05a0eb14a9c8ff345698f56a2"),
]


def main() -> int:
    cpp = [
        "// Generated by tools/gen_freebios_embed.py from the",
        "// third_party/freebios submodule -- do not hand-edit.",
        "// FreeBIOS, Copyright (c) 2013, Gilead Kutnick, BSD-2-Clause",
        "// (third_party/freebios/LICENSE.txt).",
        "",
        '#include "freebios_images.h"',
        "",
    ]
    sizes = {}
    for name, sym, want_sha1 in IMAGES:
        data = (SUB / name).read_bytes()
        got = hashlib.sha1(data).hexdigest()
        if got != want_sha1:
            raise SystemExit(
                f"{name}: sha1 {got} != pinned {want_sha1} -- refusing "
                "(update the pin only for a deliberate upstream bump)")
        sizes[sym] = len(data)
        cpp.append(f"const unsigned char {sym}[{len(data)}] = {{")
        for i in range(0, len(data), 12):
            row = ", ".join(f"0x{b:02X}" for b in data[i:i + 12])
            cpp.append(f"    {row},")
        cpp.append("};")
        cpp.append("")
        print(f"{name}: {len(data)} bytes, sha1 {got}")
    (OUT / "freebios_images.cpp").write_text("\n".join(cpp) + "\n",
                                             encoding="utf-8", newline="\n")
    header = (
        "// Generated by tools/gen_freebios_embed.py from the\n"
        "// third_party/freebios submodule -- do not hand-edit.\n"
        "// FreeBIOS, Copyright (c) 2013, Gilead Kutnick, BSD-2-Clause\n"
        "// (third_party/freebios/LICENSE.txt).\n"
        "\n"
        "#pragma once\n"
        "\n"
        f"extern const unsigned char nds_freebios9[{sizes['nds_freebios9']}];\n"
        f"extern const unsigned char nds_freebios7[{sizes['nds_freebios7']}];\n")
    (OUT / "freebios_images.h").write_text(header, encoding="utf-8",
                                           newline="\n")
    print("freebios_images.{cpp,h} written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
