#!/usr/bin/env python3
"""import_bios_symbols.py — emit per-BIOS recompile config TOMLs from the
PikalaxALT/ndsbios disassembly.

ndsbios reassembles to binaries that SHA-1-match our `bios/biosnds7.rom`
and `bios/biosnds9.rom` (verified by its own `bios.sha1`, and by
`make compare`). We import its global LABEL set as `[[extra_func]]`
entries (addr + ARM/Thumb mode + name) and declare the BIOS SWI jump
tables as `[[jump_table]]` directives.

Pipeline (mirrors gbarecomp/tools/import_bios_symbols):
  1. Build the disasm:  make -C third_party/ndsbios all
  2. `arm-none-eabi-nm -n bios{7,9}.elf` → (addr, name) for global
     text symbols (type 'T') — the function entries the author marked.
  3. Parse `bios{7,9}.s` for `(arm|thumb|non_word_aligned_thumb)_func_start
     NAME` to assign ARM/Thumb mode per name.
  4. Emit `bios/biosnds7.toml` and `bios/biosnds9.toml`.

Idempotent: rerunning overwrites the TOMLs.
"""
from __future__ import annotations
import argparse
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]

FUNC_START_RE = re.compile(
    r"^\s*(arm|thumb|non_word_aligned_thumb)_func_start\s+(\S+)")

# Per-binary facts: ELF/asm names, base, CPU, identity, and the SWI jump
# table located during the Ghidra analysis (see docs/bios_analysis.md).
BINARIES = [
    dict(
        elf="bios7.elf", asm="bios7.s", out="biosnds7.toml",
        name="NDS ARM7 BIOS", ident="biosnds7", cpu="arm7", isa="armv4t",
        base=0x00000000, size=0x4000,
        sha1="24f67bdea115a2c847c8813a262502ee1607b7df",
        swi_table=(0x00002E38, 34)),
    dict(
        elf="bios9.elf", asm="bios9.s", out="biosnds9.toml",
        name="NDS ARM9 BIOS", ident="biosnds9", cpu="arm9", isa="armv5te",
        base=0xFFFF0000, size=0x1000,
        sha1="bfaac75f101c135e32e2aaf541de6b1be4c8c62d",
        swi_table=(0xFFFF02FC, 32)),
]


def nm_globals(elf: pathlib.Path) -> list[tuple[int, str]]:
    out = subprocess.check_output(
        ["arm-none-eabi-nm", "-n", str(elf)], text=True, encoding="utf-8")
    rows = []
    for line in out.splitlines():
        p = line.split()
        if len(p) == 3 and p[1] == "T":          # global text symbol
            try:
                rows.append((int(p[0], 16), p[2]))
            except ValueError:
                pass
    return rows


def modes_from_asm(asm: pathlib.Path) -> dict[str, str]:
    m = {}
    for line in asm.read_text(encoding="utf-8", errors="replace").splitlines():
        g = FUNC_START_RE.match(line)
        if g:
            m[g.group(2)] = "arm" if g.group(1) == "arm" else "thumb"
    return m


def emit_toml(path: pathlib.Path, b: dict,
              funcs: list[tuple[int, str, str]]) -> None:
    L = []
    L += [f"# {b['out']} — recompile config for the {b['name']}.",
          "#",
          "# Generated by tools/import_bios_symbols.py from the",
          "# PikalaxALT/ndsbios disassembly (reassembles SHA-1-identical to",
          f"# bios/{b['ident']}.rom). Re-run the importer; do not hand-edit.",
          ""]
    L += ["[program]",
          f'name         = "{b["name"]}"',
          f'id           = "{b["ident"]}"',
          f'cpu          = "{b["cpu"]}"',
          f'isa          = "{b["isa"]}"',
          f"load_address = 0x{b['base']:08X}",
          f"size         = 0x{b['size']:08X}",
          f"entry_pc     = 0x{b['base']:08X}",
          "",
          "[identity]",
          f'sha1 = "{b["sha1"]}"',
          ""]
    L += ["# ── Function entries (from ndsbios global symbols) ──────────────"]
    arm = sum(1 for _, _, m in funcs if m == "arm")
    th = sum(1 for _, _, m in funcs if m == "thumb")
    L += [f"# {len(funcs)} entries: arm={arm} thumb={th}", ""]
    for addr, name, mode in funcs:
        L += ["[[extra_func]]",
              f"addr = 0x{addr:08X}",
              f'mode = "{mode}"',
              f'name = "{name}"',
              ""]
    sa, sc = b["swi_table"]
    L += ["# ── SWI dispatch table ──────────────────────────────────────────",
          "# Indexed by SWI#*4; ABS32 entries, bit0 = Thumb. Located via the",
          "# Ghidra analysis (docs/bios_analysis.md).",
          "",
          "[[jump_table]]",
          f"addr         = 0x{sa:08X}",
          "stride       = 4",
          f"count        = {sc}",
          'format       = "abs32"',
          'entries_mode = "auto"  # bit 0 of each entry encodes Thumb/ARM',
          'name         = "swi_jump_table"',
          ""]
    path.write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--disasm", type=pathlib.Path,
                    default=ROOT / "third_party" / "ndsbios")
    ap.add_argument("--outdir", type=pathlib.Path, default=ROOT / "bios")
    args = ap.parse_args()

    for b in BINARIES:
        elf = args.disasm / b["elf"]
        asm = args.disasm / b["asm"]
        if not elf.exists():
            print(f"error: {elf} missing — build first: "
                  f"make -C {args.disasm} all", file=sys.stderr)
            return 1
        rows = nm_globals(elf)
        modes = modes_from_asm(asm)
        funcs = [(a, n, modes.get(n, "arm")) for a, n in rows]
        out = args.outdir / b["out"]
        emit_toml(out, b, funcs)
        arm = sum(1 for _, _, m in funcs if m == "arm")
        th = sum(1 for _, _, m in funcs if m == "thumb")
        print(f"==> {out.name}: {len(funcs)} funcs (arm={arm} thumb={th})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
