#pragma once

// Register every build-configured game bank only when rom_sha1 matches the
// exact image supplied with NDS_TITLE_ROM_SHA1. The implementation is
// generated by runner/CMakeLists.txt from the dispatch sources in
// NDS_TITLE_BANK_DIR, so the shared runtime does not name individual games or
// assume a fixed number of overlay/runtime bank generations.
bool nds_register_configured_title_banks(const char* rom_sha1);
